# Generated by Django 3.2.8 on 2021-10-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20211012_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[(0, 'Пользователь без прав'), (1, 'Пользователь'), (2, 'Администратор')], default=0),
        ),
    ]
