# Generated by Django 3.2 on 2021-10-17 04:27

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='platform',
            managers=[
                ('platforms', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='backend.platform')),
            ],
        ),
    ]
