# Generated by Django 3.2 on 2021-10-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20211017_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='uid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
