# Generated by Django 3.2 on 2021-10-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_project_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='123', max_length=255, verbose_name='Описание категории'),
            preserve_default=False,
        ),
    ]
